# Generated by Django 3.0.6 on 2020-05-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(blank=True, max_length=4, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Stand By'), (2, 'Departed'), (3, 'Arrived')], null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=4, null=True)),
                ('employee_name', models.TextField(null=True)),
                ('floorpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.FloorPass')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_id', models.CharField(blank=True, max_length=4, null=True)),
                ('logdatetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('floorpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.FloorPass')),
            ],
        ),
        migrations.AddField(
            model_name='floorpass',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.Location'),
        ),
    ]
