# Generated by Django 3.1.1 on 2020-09-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_accr', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(blank=True, max_length=4, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(default='', max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.department')),
            ],
        ),
        migrations.CreateModel(
            name='GuardManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mi', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('employee_name', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Stand By'), (2, 'Departed'), (3, 'Arrived')], default=0, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('floorpasses', models.ManyToManyField(to='online_floorpass.FloorPass')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_id', models.CharField(blank=True, max_length=4, null=True)),
                ('logdatetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.user')),
                ('floorpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.floorpass')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_accr', models.CharField(default='', max_length=6)),
                ('departments', models.ManyToManyField(to='online_floorpass.Department')),
            ],
        ),
        migrations.AddField(
            model_name='floorpass',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_floorpass.location'),
        ),
    ]
