# Generated by Django 3.0.6 on 2020-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='departments',
            field=models.ManyToManyField(to='online_floorpass.Department'),
        ),
    ]
