# Generated by Django 3.1.1 on 2020-10-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpass',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
