# Generated by Django 3.0.6 on 2020-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0002_location_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_accr',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='location',
            name='name_accr',
            field=models.CharField(default='', max_length=6),
        ),
    ]
