# Generated by Django 3.0.6 on 2020-09-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0003_auto_20200921_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpass',
            name='reference_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
