# Generated by Django 3.0.6 on 2020-09-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0004_floorpass_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpass',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
