# Generated by Django 3.0.6 on 2020-09-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0005_floorpass_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorpass',
            name='reference_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
