# Generated by Django 3.1.1 on 2020-09-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_floorpass', '0008_auto_20200924_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorpass',
            old_name='last_modifie',
            new_name='last_modified',
        ),
    ]
